import type { ModelProviderConfig } from "openclaw/plugin-sdk/provider-model-shared";

export const GMICLOUD_BASE_URL = "https://api.gmi-serving.com/v1";
export const GMICLOUD_DEFAULT_MODEL_ID = "anthropic/claude-opus-4.6";
const GMICLOUD_DEFAULT_MAX_TOKENS = 8192;

export function buildGmicloudProvider(): ModelProviderConfig {
  return {
    baseUrl: GMICLOUD_BASE_URL,
    api: "openai-completions",
    models: [
      {
        id: "anthropic/claude-opus-4.6",
        name: "Claude Opus 4.6",
        reasoning: true,
        input: ["text"],
        cost: { input: 5.0, output: 25.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "anthropic/claude-sonnet-4.6",
        name: "Claude Sonnet 4.6",
        reasoning: true,
        input: ["text"],
        cost: { input: 3.0, output: 15.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 200000,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "openai/gpt-5.4",
        name: "OpenAI GPT 5.4",
        reasoning: true,
        input: ["text"],
        cost: { input: 2.5, output: 15.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "openai/gpt-5.4-pro",
        name: "OpenAI GPT 5.4 Pro",
        reasoning: true,
        input: ["text"],
        cost: { input: 30.0, output: 180.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "openai/gpt-5.4-mini",
        name: "OpenAI GPT 5.4 Mini",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.75, output: 4.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "openai/gpt-5.4-nano",
        name: "OpenAI GPT 5.4 Nano",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.2, output: 1.25, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.07, output: 0.28, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "google/gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        reasoning: true,
        input: ["text"],
        cost: { input: 2.0, output: 12.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 1048576,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "google/gemini-3.1-flash-lite-preview",
        name: "Gemini 3.1 Flash Lite Preview",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.25, output: 1.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 1048576,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "zai-org/GLM-5-FP8",
        name: "ZAI GLM 5 FP8",
        reasoning: true,
        input: ["text"],
        cost: { input: 1.0, output: 3.2, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "zai-org/GLM-4.6",
        name: "GLM 4.6",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.6, output: 2.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 204800,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: GMICLOUD_DEFAULT_MODEL_ID,
        name: "Claude Opus 4.6",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.28, output: 0.88, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 163840,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.1",
        name: "DeepSeek V3.1",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.27, output: 1.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 163840,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2",
        name: "DeepSeek V3.2",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.2, output: 0.32, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 163840,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "moonshotai/Kimi-K2.5",
        name: "Kimi K2.5",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.6, output: 3.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "moonshotai/Kimi-K2-Thinking",
        name: "Kimi K2 Thinking",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.8, output: 1.2, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "moonshotai/Kimi-K2-Instruct-0905",
        name: "Kimi K2 Instruct 0905",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.3, output: 1.7, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
        name: "Qwen3 Next 80B A3B Instruct",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.15, output: 1.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
        name: "Qwen3 Coder 480B A35B Instruct FP8",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.29, output: 1.2, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Thinking-2507-FP8",
        name: "Qwen3 235B A22B Thinking 2507 FP8",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.6, output: 3.0, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "Qwen/Qwen3-32B-FP8",
        name: "Qwen3 32B FP8",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.1, output: 0.6, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 32768,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
      {
        id: "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        name: "Llama 4 Scout 17B 16E Instruct",
        reasoning: false,
        input: ["text"],
        cost: { input: 0.08, output: 0.5, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 1048576,
        maxTokens: GMICLOUD_DEFAULT_MAX_TOKENS,
      },
    ],
  };
}
