export const QINIU_BASE_URL = "https://api.qnaigc.com";
export const QINIU_DEFAULT_MODEL_ID = "minimax/minimax-m2.5";
export const QINIU_DEFAULT_MODEL_REF = `qiniu/${QINIU_DEFAULT_MODEL_ID}`;
export const QINIU_DEFAULT_MODEL_NAME = "MiniMax M2.5";

export type QiniuModelCatalogEntry = {
  id: string;
  name: string;
  reasoning: boolean;
  input: Array<"text" | "image">;
  contextWindow?: number;
  maxTokens?: number;
};

export const QINIU_MODEL_CATALOG: QiniuModelCatalogEntry[] = [
  // MiniMax
  {
    id: "minimax/minimax-m2.5",
    name: "MiniMax M2.5",
    reasoning: true,
    input: ["text"],
    contextWindow: 200000,
    maxTokens: 128000,
  },
  {
    id: "minimax/minimax-m2.1",
    name: "MiniMax M2.1",
    reasoning: true,
    input: ["text"],
    contextWindow: 200000,
    maxTokens: 128000,
  },
  {
    id: "minimax/minimax-m2",
    name: "MiniMax M2",
    reasoning: true,
    input: ["text"],
    contextWindow: 200000,
    maxTokens: 128000,
  },
  {
    id: "MiniMax-M1",
    name: "MiniMax M1",
    reasoning: true,
    input: ["text"],
    contextWindow: 1000000,
    maxTokens: 131072,
  },
  // DeepSeek
  {
    id: "deepseek/deepseek-v3.2-exp",
    name: "DeepSeek V3.2 Exp",
    reasoning: false,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 8192,
  },
  {
    id: "deepseek/deepseek-v3.2-exp-thinking",
    name: "DeepSeek V3.2 Exp Thinking",
    reasoning: true,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 32768,
  },
  {
    id: "deepseek/deepseek-v3.2-251201",
    name: "DeepSeek V3.2 251201",
    reasoning: false,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 8192,
  },
  {
    id: "deepseek/deepseek-v3.1-terminus",
    name: "DeepSeek V3.1 Terminus",
    reasoning: false,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 8192,
  },
  {
    id: "deepseek/deepseek-v3.1-terminus-thinking",
    name: "DeepSeek V3.1 Terminus Thinking",
    reasoning: true,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 32768,
  },
  {
    id: "deepseek-v3.1",
    name: "DeepSeek V3.1",
    reasoning: false,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 8192,
  },
  {
    id: "deepseek-v3-0324",
    name: "DeepSeek V3 0324",
    reasoning: false,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 8192,
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    reasoning: false,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 8192,
  },
  {
    id: "deepseek-r1-0528",
    name: "DeepSeek R1 0528",
    reasoning: true,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 32768,
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    reasoning: true,
    input: ["text"],
    contextWindow: 65536,
    maxTokens: 32768,
  },
  // Qwen
  {
    id: "qwen3-235b-a22b-thinking-2507",
    name: "Qwen3 235B A22B Thinking 2507",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-235b-a22b-instruct-2507",
    name: "Qwen3 235B A22B Instruct 2507",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-235b-a22b",
    name: "Qwen3 235B A22B",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-coder-480b-a35b-instruct",
    name: "Qwen3 Coder 480B A35B Instruct",
    reasoning: false,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 32768,
  },
  {
    id: "qwen3-max",
    name: "Qwen3 Max",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-max-preview",
    name: "Qwen3 Max Preview",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-30b-a3b",
    name: "Qwen3 30B A3B",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-30b-a3b-thinking-2507",
    name: "Qwen3 30B A3B Thinking 2507",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-30b-a3b-instruct-2507",
    name: "Qwen3 30B A3B Instruct 2507",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-next-80b-a3b-thinking",
    name: "Qwen3 Next 80B A3B Thinking",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen3-next-80b-a3b-instruct",
    name: "Qwen3 Next 80B A3B Instruct",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen-max-2025-01-25",
    name: "Qwen Max 2025-01-25",
    reasoning: false,
    input: ["text"],
    contextWindow: 32768,
    maxTokens: 8192,
  },
  {
    id: "qwen-turbo",
    name: "Qwen Turbo",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
  {
    id: "qwen3-vl-30b-a3b-thinking",
    name: "Qwen3 VL 30B A3B Thinking",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "qwen-vl-max-2025-01-25",
    name: "Qwen VL Max 2025-01-25",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 32768,
    maxTokens: 8192,
  },
  {
    id: "qwen2.5-vl-72b-instruct",
    name: "Qwen2.5 VL 72B Instruct",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
  {
    id: "qwen2.5-vl-7b-instruct",
    name: "Qwen2.5 VL 7B Instruct",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
  // GLM (Z-AI / Zhipu)
  {
    id: "z-ai/glm-5",
    name: "GLM-5",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 65536,
  },
  {
    id: "z-ai/glm-4.7",
    name: "GLM-4.7",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
  {
    id: "z-ai/glm-4.6",
    name: "GLM-4.6",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
  {
    id: "glm-4.5",
    name: "GLM-4.5",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
  {
    id: "glm-4.5-air",
    name: "GLM-4.5 Air",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
  // Kimi (Moonshot)
  {
    id: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    reasoning: true,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 65536,
  },
  {
    id: "moonshotai/kimi-k2-thinking",
    name: "Kimi K2 Thinking",
    reasoning: true,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 65536,
  },
  {
    id: "moonshotai/kimi-k2-0905",
    name: "Kimi K2 0905",
    reasoning: false,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 65536,
  },
  {
    id: "kimi-k2",
    name: "Kimi K2",
    reasoning: false,
    input: ["text"],
    contextWindow: 262144,
    maxTokens: 65536,
  },
  // Doubao (ByteDance)
  {
    id: "doubao-seed-1.6-thinking",
    name: "Doubao Seed 1.6 Thinking",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "doubao-seed-1.6",
    name: "Doubao Seed 1.6",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "doubao-seed-1.6-flash",
    name: "Doubao Seed 1.6 Flash",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "doubao-1.5-thinking-pro",
    name: "Doubao 1.5 Thinking Pro",
    reasoning: true,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 32768,
  },
  {
    id: "doubao-1.5-vision-pro",
    name: "Doubao 1.5 Vision Pro",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 131072,
    maxTokens: 16384,
  },
  {
    id: "doubao-1.5-pro-32k",
    name: "Doubao 1.5 Pro 32K",
    reasoning: false,
    input: ["text"],
    contextWindow: 32768,
    maxTokens: 8192,
  },
  // Meituan
  {
    id: "meituan/longcat-flash-lite",
    name: "Longcat Flash Lite",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
  // Xiaomi
  {
    id: "xiaomi/mimo-v2-flash",
    name: "MiMo V2 Flash",
    reasoning: false,
    input: ["text"],
    contextWindow: 131072,
    maxTokens: 8192,
  },
];

export const QINIU_DEFAULT_CONTEXT_WINDOW = 200000;
export const QINIU_DEFAULT_MAX_TOKENS = 128000;
export const QINIU_DEFAULT_COST = {
  input: 0,
  output: 0,
  cacheRead: 0,
  cacheWrite: 0,
} as const;
