import { beforeEach, describe, expect, it, vi } from "vitest";
import type { OpenClawConfig } from "../config/types.js";

const mocks = vi.hoisted(() => ({
  loadConfig: vi.fn<() => OpenClawConfig>(),
  writeConfigFile: vi.fn(async (_cfg: OpenClawConfig) => {}),
}));

vi.mock("../config/config.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../config/config.js")>();
  return {
    ...actual,
    loadConfig: mocks.loadConfig,
    writeConfigFile: mocks.writeConfigFile,
  };
});

import { ensureBrowserControlAuth } from "./control-auth.js";

describe("ensureBrowserControlAuth", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    mocks.loadConfig.mockClear();
    mocks.writeConfigFile.mockClear();
    // Default: loadConfig returns empty config (no gateway auth).
    mocks.loadConfig.mockReturnValue({});
  });

  async function expectNoAutoGeneratedAuth(cfg: OpenClawConfig): Promise<void> {
    const result = await ensureBrowserControlAuth({
      cfg,
      env: { OPENCLAW_BROWSER_AUTO_AUTH: "1" } as unknown as NodeJS.ProcessEnv,
    });
    expect(result.generatedToken).toBeUndefined();
    expect(result.auth.token).toBeUndefined();
    expect(result.auth.password).toBeUndefined();
  }

  describe("trusted-proxy mode", () => {
    it("should not auto-generate token when auth mode is trusted-proxy", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "trusted-proxy",
            trustedProxy: {
              userHeader: "x-forwarded-user",
            },
          },
          trustedProxies: ["192.168.1.1"],
        },
      };
      await expectNoAutoGeneratedAuth(cfg);
    });
  });

  describe("password mode", () => {
    it("should not auto-generate token when auth mode is password (even if password not set)", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "password",
          },
        },
      };
      await expectNoAutoGeneratedAuth(cfg);
    });
  });

  describe("none mode", () => {
    it("should auto-generate browser token even when gateway auth mode is none", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "none",
          },
        },
      };
      mocks.loadConfig.mockReturnValue(cfg);

      const result = await ensureBrowserControlAuth({
        cfg,
        env: { OPENCLAW_BROWSER_AUTO_AUTH: "1" } as unknown as NodeJS.ProcessEnv,
      });

      // The browser control surface must always be protected, even when the
      // gateway itself runs in auth mode "none".
      expect(result.generatedToken).toBeDefined();
      expect(typeof result.generatedToken).toBe("string");
      expect(result.auth.token).toBeDefined();
    });
  });

  describe("token mode", () => {
    it("should return existing token if configured", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "token",
            token: "existing-token-123",
          },
        },
      };

      const result = await ensureBrowserControlAuth({
        cfg,
        env: { OPENCLAW_BROWSER_AUTO_AUTH: "1" } as unknown as NodeJS.ProcessEnv,
      });

      expect(result.generatedToken).toBeUndefined();
      expect(result.auth.token).toBe("existing-token-123");
    });

    it("should skip auto-generation in test environment", async () => {
      const cfg: OpenClawConfig = {
        gateway: {
          auth: {
            mode: "token",
          },
        },
      };

      const result = await ensureBrowserControlAuth({
        cfg,
        env: { NODE_ENV: "test" } as NodeJS.ProcessEnv,
      });

      expect(result.generatedToken).toBeUndefined();
      expect(result.auth.token).toBeUndefined();
    });
  });
});
