"use client";

import { useState } from "react";
import { useAutoRefresh } from "@/hooks/use-auto-refresh";
import { GlassCard } from "@/components/ui/glass-card";
import { PriorityBadge, EffortBadge } from "@/components/ui/priority-badge";
import { EmptyState } from "@/components/ui/empty-state";
import { SkeletonCard } from "@/components/ui/skeleton-card";
import { StaggerGrid, StaggerItem } from "@/components/ui/stagger-grid";
import { CheckCircle, XCircle, ListTodo, Filter } from "lucide-react";
import type { SuggestedTask } from "@/lib/types";

const categoryEmojis: Record<string, string> = {
  Revenue: "💰",
  Product: "🛠️",
  Community: "👥",
  Content: "📝",
  Operations: "⚙️",
  Clients: "🤝",
  Trading: "📈",
  Brand: "🎨",
};

export function SuggestedTasksView() {
  const { data: tasks, loading, refresh } = useAutoRefresh<SuggestedTask[]>("/api/suggested-tasks");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [categoryFilter, setCategoryFilter] = useState<string>("all");

  async function handleAction(taskId: string, action: "approve" | "reject") {
    await fetch("/api/suggested-tasks", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id: taskId, action }),
    });
    refresh();
  }

  const filtered = (tasks || []).filter((t) => {
    if (statusFilter !== "all" && t.status !== statusFilter) return false;
    if (categoryFilter !== "all" && t.category !== categoryFilter) return false;
    return true;
  });

  const categories = [...new Set((tasks || []).map((t) => t.category))];

  // Group by category
  const grouped = filtered.reduce<Record<string, SuggestedTask[]>>((acc, t) => {
    (acc[t.category] = acc[t.category] || []).push(t);
    return acc;
  }, {});

  if (loading) {
    return (
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <SkeletonCard key={i} lines={4} />
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Filter bar */}
      <div className="flex items-center gap-2 flex-wrap">
        <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
          <Filter className="w-3.5 h-3.5" />
          <span>Filter:</span>
        </div>
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="text-xs bg-white/[0.03] border border-white/[0.06] rounded-lg px-2 py-1.5 text-foreground"
        >
          <option value="all">All Status</option>
          <option value="pending">Pending</option>
          <option value="approved">Approved</option>
          <option value="rejected">Rejected</option>
        </select>
        <select
          value={categoryFilter}
          onChange={(e) => setCategoryFilter(e.target.value)}
          className="text-xs bg-white/[0.03] border border-white/[0.06] rounded-lg px-2 py-1.5 text-foreground"
        >
          <option value="all">All Categories</option>
          {categories.map((c) => (
            <option key={c} value={c}>{c}</option>
          ))}
        </select>
      </div>

      {Object.keys(grouped).length === 0 ? (
        <EmptyState
          icon={ListTodo}
          title="No suggested tasks"
          description="Tasks will appear here when generated by your agents."
        />
      ) : (
        Object.entries(grouped).map(([category, categoryTasks]) => (
          <div key={category}>
            <h3 className="text-sm font-medium mb-2 flex items-center gap-1.5">
              <span>{categoryEmojis[category] || "📋"}</span>
              {category}
              <span className="text-[10px] text-muted-foreground">({categoryTasks.length})</span>
            </h3>
            <StaggerGrid columns="grid-cols-1 sm:grid-cols-2">
              {categoryTasks.map((task) => (
                <StaggerItem key={task.id}>
                  <GlassCard padding="sm" className={task.status !== "pending" ? "opacity-60" : ""}>
                    <div className="flex items-start justify-between mb-2">
                      <h4 className="text-xs font-semibold pr-2">{task.title}</h4>
                      <div className="flex gap-1 shrink-0">
                        <PriorityBadge priority={task.priority} />
                        <EffortBadge effort={task.effort} />
                      </div>
                    </div>
                    <p className="text-[11px] text-muted-foreground mb-2 line-clamp-2">{task.reasoning}</p>
                    <p className="text-[11px] text-foreground/80 mb-3">
                      <span className="text-muted-foreground">Next: </span>
                      {task.nextAction}
                    </p>
                    {task.status === "pending" && (
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleAction(task.id, "approve")}
                          className="flex items-center gap-1 px-2.5 py-1 text-[10px] font-medium rounded-md bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 hover:bg-emerald-500/20 transition-colors"
                        >
                          <CheckCircle className="w-3 h-3" /> Approve
                        </button>
                        <button
                          onClick={() => handleAction(task.id, "reject")}
                          className="flex items-center gap-1 px-2.5 py-1 text-[10px] font-medium rounded-md bg-red-500/10 text-red-400 border border-red-500/20 hover:bg-red-500/20 transition-colors"
                        >
                          <XCircle className="w-3 h-3" /> Reject
                        </button>
                      </div>
                    )}
                    {task.status !== "pending" && (
                      <span className={`text-[10px] font-medium ${task.status === "approved" ? "text-emerald-400" : "text-red-400"}`}>
                        {task.status.toUpperCase()}
                      </span>
                    )}
                  </GlassCard>
                </StaggerItem>
              ))}
            </StaggerGrid>
          </div>
        ))
      )}
    </div>
  );
}
