/**
 * Lightweight Adaptive Card renderer for Lit-based web UI.
 *
 * Covers AC v1.6 elements generated by adaptive-cards-mcp without pulling
 * in the full `adaptivecards` npm package (~60 KB). Unknown element types
 * are silently skipped.
 */

import { html, nothing, type TemplateResult } from "lit";
import { unsafeHTML } from "lit/directives/unsafe-html.js";
import { toSanitizedMarkdownHtml } from "../markdown.ts";
import { openExternalUrlSafe } from "../open-external-url.ts";
import type { ParsedAdaptiveCard } from "./adaptive-card-parse.ts";

type ACElement = Record<string, unknown>;

// ---------------------------------------------------------------------------
// Template data binding
// ---------------------------------------------------------------------------

/** Expand `${expression}` placeholders against template data. */
function bindTemplateData(obj: unknown, data: Record<string, unknown>): unknown {
  if (typeof obj === "string") {
    return obj.replace(/\$\{([^}]+)\}/g, (_match, expr: string) => {
      const path = expr.trim().replace(/^\$root\./, "");
      const val = resolvePath(data, path);
      if (val === undefined) {
        return "";
      }
      return typeof val === "object"
        ? JSON.stringify(val)
        : String(val as string | number | boolean);
    });
  }
  if (Array.isArray(obj)) {
    return obj.map((item) => bindTemplateData(item, data));
  }
  if (obj && typeof obj === "object") {
    const result: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj)) {
      result[k] = bindTemplateData(v, data);
    }
    return result;
  }
  return obj;
}

function resolvePath(obj: unknown, path: string): unknown {
  let current: unknown = obj;
  for (const key of path.split(".")) {
    if (current == null || typeof current !== "object") {
      return undefined;
    }
    current = (current as Record<string, unknown>)[key];
  }
  return current;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Render a parsed adaptive card as a Lit TemplateResult. */
export function renderAdaptiveCard(parsed: ParsedAdaptiveCard): TemplateResult {
  let card = parsed.card as unknown;
  if (parsed.templateData && typeof parsed.templateData === "object") {
    card = bindTemplateData(card, parsed.templateData as Record<string, unknown>);
  }
  const c = card as ParsedAdaptiveCard["card"];
  return html`
    <div class="ac-card">
      ${renderElements(c.body)}
      ${Array.isArray(c.actions) && c.actions.length ? renderActions(c.actions as ACElement[]) : nothing}
    </div>
  `;
}

// ---------------------------------------------------------------------------
// Element dispatch
// ---------------------------------------------------------------------------

function renderElements(items: unknown[]): TemplateResult[] {
  const results: TemplateResult[] = [];
  for (const item of items) {
    if (!item || typeof item !== "object") {
      continue;
    }
    const el = item as ACElement;
    const rendered = renderElement(el);
    if (rendered !== nothing) {
      results.push(rendered);
    }
  }
  return results;
}

function renderElement(el: ACElement): TemplateResult | typeof nothing {
  const type = typeof el.type === "string" ? el.type : "";
  switch (type) {
    case "TextBlock":
      return renderTextBlock(el);
    case "RichTextBlock":
      return renderRichTextBlock(el);
    case "CodeBlock":
      return renderCodeBlock(el);
    case "FactSet":
      return renderFactSet(el);
    case "ColumnSet":
      return renderColumnSet(el);
    case "Column":
      return renderColumn(el);
    case "Container":
      return renderContainer(el);
    case "Image":
      return renderImage(el);
    case "ImageSet":
      return renderImageSet(el);
    case "Table":
      return renderTable(el);
    case "ActionSet":
      return renderActionSet(el);
    case "Carousel":
      return renderCarousel(el);
    case "Accordion":
      return renderAccordion(el);
    case "TabSet":
      return renderTabSet(el);
    case "Rating":
      return renderRating(el);
    case "ProgressBar":
      return renderProgressBar(el);
    case "Badge":
      return renderBadge(el);
    case "CompoundButton":
      return renderCompoundButton(el);
    case "Icon":
      return renderIcon(el);
    case "List":
      return renderList(el);
    case "Input.Text":
      return renderInputText(el);
    case "Input.Number":
      return renderInputNumber(el);
    case "Input.Date":
      return renderInputDate(el);
    case "Input.Time":
      return renderInputTime(el);
    case "Input.Toggle":
      return renderInputToggle(el);
    case "Input.ChoiceSet":
      return renderInputChoiceSet(el);
    default:
      // Chart types: render as simple data display
      if (type.startsWith("Chart.")) {
        return renderChart(el);
      }
      return nothing;
  }
}

// ---------------------------------------------------------------------------
// Body element renderers
// ---------------------------------------------------------------------------

function renderTextBlock(el: ACElement): TemplateResult {
  const text = typeof el.text === "string" ? el.text : "";
  const weight = el.weight === "Bolder" ? "ac-bold" : "";
  const isSubtle = el.isSubtle === true ? "ac-subtle" : "";
  const sizeClass = sizeToClass(el.size);
  const wrapClass = el.wrap === false ? "ac-nowrap" : "";
  const headingClass = el.style === "heading" ? "ac-heading" : "";

  // AC spec allows basic markdown in TextBlock text
  const hasMarkdown = /[*_`[#]/.test(text);
  const content = hasMarkdown ? unsafeHTML(toSanitizedMarkdownHtml(text)) : text;

  return html`<div class="ac-text ${weight} ${isSubtle} ${sizeClass} ${wrapClass} ${headingClass}">
    ${content}
  </div>`;
}

function renderRichTextBlock(el: ACElement): TemplateResult {
  const inlines = Array.isArray(el.inlines) ? el.inlines : [];
  return html`
    <div class="ac-richtext">
      ${inlines.map((inline) => {
        if (typeof inline === "string") {
          return html`<span>${inline}</span>`;
        }
        if (inline && typeof inline === "object") {
          const run = inline as ACElement;
          const text = typeof run.text === "string" ? run.text : "";
          const bold = run.weight === "Bolder" || run.fontType === "Bold";
          const italic = run.italic === true;
          const strike = run.strikethrough === true;
          const highlight = run.highlight === true;
          const subtle = run.isSubtle === true;
          const cls = [
            bold ? "ac-bold" : "",
            italic ? "ac-italic" : "",
            strike ? "ac-strike" : "",
            highlight ? "ac-highlight" : "",
            subtle ? "ac-subtle" : "",
          ]
            .filter(Boolean)
            .join(" ");
          if (
            typeof run.selectAction === "object" &&
            (run.selectAction as ACElement).type === "Action.OpenUrl"
          ) {
            const url =
              typeof (run.selectAction as ACElement).url === "string"
                ? ((run.selectAction as ACElement).url as string)
                : "";
            return html`<a class="ac-inline-link ${cls}" href="${url}" @click=${(e: Event) => {
              e.preventDefault();
              openExternalUrlSafe(url);
            }}>${text}</a>`;
          }
          return html`<span class="${cls}">${text}</span>`;
        }
        return nothing;
      })}
    </div>
  `;
}

function renderCodeBlock(el: ACElement): TemplateResult {
  const code = typeof el.codeSnippet === "string" ? el.codeSnippet : "";
  const language = typeof el.language === "string" ? el.language : "";
  return html`
    <div class="ac-codeblock">
      ${language ? html`<div class="ac-codeblock__lang">${language}</div>` : nothing}
      <pre class="ac-codeblock__pre"><code>${code}</code></pre>
    </div>
  `;
}

function renderFactSet(el: ACElement): TemplateResult {
  const facts = Array.isArray(el.facts) ? (el.facts as ACElement[]) : [];
  return html`
    <dl class="ac-factset">
      ${facts.map(
        (f) => html`
          <dt class="ac-factset__key">${typeof f.title === "string" ? f.title : ""}</dt>
          <dd class="ac-factset__val">${typeof f.value === "string" ? f.value : ""}</dd>
        `,
      )}
    </dl>
  `;
}

function renderColumnSet(el: ACElement): TemplateResult {
  const columns = Array.isArray(el.columns) ? (el.columns as ACElement[]) : [];
  return html`
    <div class="ac-columnset">
      ${columns.map((col) => renderElement({ type: "Column", ...col }))}
    </div>
  `;
}

function renderColumn(el: ACElement): TemplateResult {
  const items = Array.isArray(el.items) ? el.items : [];
  const width = typeof el.width === "string" ? el.width : "auto";
  const flex = width === "stretch" ? "1 1 0%" : width === "auto" ? "0 0 auto" : `0 0 ${width}`;
  return html`
    <div class="ac-column" style="flex: ${flex}">
      ${renderElements(items as unknown[])}
    </div>
  `;
}

function renderContainer(el: ACElement): TemplateResult {
  const items = Array.isArray(el.items) ? el.items : [];
  const style = el.style === "emphasis" ? "ac-container--emphasis" : "";
  const bleed = el.bleed === true ? "ac-container--bleed" : "";
  return html`
    <div class="ac-container ${style} ${bleed}">
      ${renderElements(items as unknown[])}
    </div>
  `;
}

function renderImage(el: ACElement): TemplateResult | typeof nothing {
  const url = typeof el.url === "string" ? el.url : "";
  const alt = typeof el.altText === "string" ? el.altText : "";
  const sizeClass = imageSizeClass(el.size);
  const styleClass = el.style === "person" ? "ac-img-person" : "";
  if (!url) {
    return nothing;
  }
  return html`<img class="ac-image ${sizeClass} ${styleClass}" src="${url}" alt="${alt}" />`;
}

function renderImageSet(el: ACElement): TemplateResult {
  const images = Array.isArray(el.images) ? (el.images as ACElement[]) : [];
  const sizeClass = imageSizeClass(el.imageSize);
  return html`
    <div class="ac-imageset ${sizeClass}">
      ${images.map((img) => {
        const url = typeof img.url === "string" ? img.url : "";
        const alt = typeof img.altText === "string" ? img.altText : "";
        return url ? html`<img class="ac-imageset__img" src="${url}" alt="${alt}" />` : nothing;
      })}
    </div>
  `;
}

function renderTable(el: ACElement): TemplateResult {
  const columns = Array.isArray(el.columns) ? (el.columns as ACElement[]) : [];
  const rows = Array.isArray(el.rows) ? (el.rows as ACElement[]) : [];
  const showHeader = el.firstRowAsHeader !== false && rows.length > 0;
  const headerRow = showHeader ? rows[0] : null;
  const bodyRows = showHeader ? rows.slice(1) : rows;

  return html`
    <table class="ac-table">
      ${
        headerRow
          ? html`<thead>
              <tr>
                ${renderTableCells(headerRow, columns, true)}
              </tr>
            </thead>`
          : nothing
      }
      <tbody>
        ${bodyRows.map(
          (row) =>
            html`<tr>
              ${renderTableCells(row, columns, false)}
            </tr>`,
        )}
      </tbody>
    </table>
  `;
}

function renderTableCells(
  row: ACElement,
  _columns: ACElement[],
  isHeader: boolean,
): TemplateResult[] {
  const cells = Array.isArray(row.cells) ? (row.cells as ACElement[]) : [];
  return cells.map((cell) => {
    const items = Array.isArray(cell.items) ? cell.items : [];
    const firstEl = items[0] as ACElement | undefined;
    const text =
      items.length === 1 && firstEl?.type === "TextBlock" && typeof firstEl.text === "string"
        ? firstEl.text
        : null;
    const content = text !== null ? text : renderElements(items as unknown[]);
    return isHeader
      ? html`<th class="ac-table__th">${content}</th>`
      : html`<td class="ac-table__td">${content}</td>`;
  });
}

function renderActionSet(el: ACElement): TemplateResult {
  const actions = Array.isArray(el.actions) ? (el.actions as ACElement[]) : [];
  if (actions.length === 0) {
    return nothing as unknown as TemplateResult;
  }
  return html`
    <div class="ac-actionset">
      ${actions.map((a) => renderAction(a))}
    </div>
  `;
}

function renderCarousel(el: ACElement): TemplateResult {
  const pages = Array.isArray(el.pages) ? (el.pages as ACElement[]) : [];
  if (pages.length === 0) {
    return nothing as unknown as TemplateResult;
  }
  return html`
    <div class="ac-carousel">
      ${pages.map(
        (page, i) => html`
          <div class="ac-carousel__page">
            <div class="ac-carousel__badge">${i + 1} / ${pages.length}</div>
            ${Array.isArray(page.items) ? renderElements(page.items as unknown[]) : nothing}
          </div>
        `,
      )}
    </div>
  `;
}

function renderAccordion(el: ACElement): TemplateResult {
  const panels = Array.isArray(el.panels) ? (el.panels as ACElement[]) : [];
  return html`
    <div class="ac-accordion">
      ${panels.map((panel) => {
        const title = typeof panel.title === "string" ? panel.title : "Section";
        const card = panel.card as ACElement | undefined;
        const items = card && Array.isArray(card.body) ? card.body : [];
        return html`
          <details class="ac-accordion__panel">
            <summary class="ac-accordion__title">${title}</summary>
            <div class="ac-accordion__body">
              ${renderElements(items as unknown[])}
            </div>
          </details>
        `;
      })}
    </div>
  `;
}

function renderTabSet(el: ACElement): TemplateResult {
  const tabs = Array.isArray(el.tabs) ? (el.tabs as ACElement[]) : [];
  if (tabs.length === 0) {
    return nothing as unknown as TemplateResult;
  }
  // Render tabs as accordion-style details since pure CSS tabs need JS state
  return html`
    <div class="ac-tabset">
      ${tabs.map((tab) => {
        const title = typeof tab.title === "string" ? tab.title : "Tab";
        const card = tab.card as ACElement | undefined;
        const items = card && Array.isArray(card.body) ? card.body : [];
        return html`
          <details class="ac-tabset__tab">
            <summary class="ac-tabset__label">${title}</summary>
            <div class="ac-tabset__body">
              ${renderElements(items as unknown[])}
            </div>
          </details>
        `;
      })}
    </div>
  `;
}

function renderRating(el: ACElement): TemplateResult {
  const value = typeof el.value === "number" ? el.value : 0;
  const max = typeof el.max === "number" ? el.max : 5;
  const label = typeof el.label === "string" ? el.label : "";
  const filled = Math.round(Math.min(value, max));
  const stars = Array.from({ length: max }, (_, i) => (i < filled ? "\u2605" : "\u2606")).join("");
  return html`
    <div class="ac-rating">
      <span class="ac-rating__stars">${stars}</span>
      <span class="ac-rating__value">${value}/${max}</span>
      ${label ? html`<span class="ac-rating__label">${label}</span>` : nothing}
    </div>
  `;
}

function renderProgressBar(el: ACElement): TemplateResult {
  const value = typeof el.value === "number" ? Math.min(Math.max(el.value, 0), 100) : 0;
  const label = typeof el.label === "string" ? el.label : "";
  const color = typeof el.color === "string" ? el.color : "";
  const colorClass = color ? `ac-progress--${color.toLowerCase()}` : "";
  return html`
    <div class="ac-progress ${colorClass}">
      ${label ? html`<div class="ac-progress__label">${label}</div>` : nothing}
      <div class="ac-progress__track">
        <div class="ac-progress__fill" style="width: ${value}%"></div>
      </div>
      <div class="ac-progress__value">${value}%</div>
    </div>
  `;
}

function renderBadge(el: ACElement): TemplateResult {
  const text = typeof el.text === "string" ? el.text : "";
  const appearance = typeof el.appearance === "string" ? el.appearance : "default";
  return html`<span class="ac-badge ac-badge--${appearance}">${text}</span>`;
}

function renderCompoundButton(el: ACElement): TemplateResult {
  const title = typeof el.title === "string" ? el.title : "";
  const description = typeof el.description === "string" ? el.description : "";
  const icon = typeof el.icon === "string" ? el.icon : "";
  return html`
    <button class="ac-compound-btn" type="button" @click=${() => dispatchCardAction(el)}>
      ${icon ? html`<span class="ac-compound-btn__icon">${icon}</span>` : nothing}
      <span class="ac-compound-btn__content">
        <span class="ac-compound-btn__title">${title}</span>
        ${description ? html`<span class="ac-compound-btn__desc">${description}</span>` : nothing}
      </span>
    </button>
  `;
}

function renderIcon(el: ACElement): TemplateResult {
  const name = typeof el.name === "string" ? el.name : "";
  const size = typeof el.size === "string" ? el.size : "";
  const color = typeof el.color === "string" ? el.color : "";
  const style = el.style === "filled" ? "ac-icon--filled" : "";
  const sizeClass = size ? `ac-icon--${size.toLowerCase()}` : "";
  const colorClass = color ? `ac-icon--${color.toLowerCase()}` : "";
  return html`<span class="ac-icon ${sizeClass} ${colorClass} ${style}">${name}</span>`;
}

function renderList(el: ACElement): TemplateResult {
  const items = Array.isArray(el.items) ? (el.items as ACElement[]) : [];
  const isOrdered = el.style === "ordered";
  const listItems = items.map((item) => {
    const text = typeof item.text === "string" ? item.text : "";
    const icon = item.icon as ACElement | undefined;
    return html`
      <li class="ac-list__item">
        ${icon && typeof icon === "object" && icon.name ? renderIcon(icon) : nothing}
        <span>${text}</span>
      </li>
    `;
  });
  return isOrdered
    ? html`<ol class="ac-list ac-list--ordered">${listItems}</ol>`
    : html`<ul class="ac-list ac-list--unordered">${listItems}</ul>`;
}

function renderChart(el: ACElement): TemplateResult {
  const type = typeof el.type === "string" ? el.type : "";
  const title = typeof el.title === "string" ? el.title : "";
  const chartData = Array.isArray(el.data) ? (el.data as ACElement[]) : [];
  const chartType = type.replace("Chart.", "").toLowerCase();

  return html`
    <div class="ac-chart">
      ${title ? html`<div class="ac-chart__title">${title}</div>` : nothing}
      <div class="ac-chart__type">${chartType} chart</div>
      ${
        chartData.length > 0
          ? html`<dl class="ac-chart__data">
            ${chartData.map((point) => {
              const label =
                typeof point.label === "string"
                  ? point.label
                  : typeof point.x === "string"
                    ? point.x
                    : "";
              const value = point.value ?? point.y ?? "";
              return html`
                <dt class="ac-chart__label">${label}</dt>
                <dd class="ac-chart__value">${value}</dd>
              `;
            })}
          </dl>`
          : nothing
      }
    </div>
  `;
}

// ---------------------------------------------------------------------------
// Input element renderers (read-only in chat context)
// ---------------------------------------------------------------------------

function renderInputText(el: ACElement): TemplateResult {
  const label = typeof el.label === "string" ? el.label : "";
  const placeholder = typeof el.placeholder === "string" ? el.placeholder : "";
  const value = typeof el.value === "string" ? el.value : "";
  const isMultiline = el.isMultiline === true;
  return html`
    <div class="ac-input">
      ${label ? html`<label class="ac-input__label">${label}</label>` : nothing}
      ${
        isMultiline
          ? html`<textarea class="ac-input__field ac-input__textarea" placeholder="${placeholder}" .value="${value}" readonly></textarea>`
          : html`<input class="ac-input__field" type="text" placeholder="${placeholder}" .value="${value}" readonly />`
      }
    </div>
  `;
}

function renderInputNumber(el: ACElement): TemplateResult {
  const label = typeof el.label === "string" ? el.label : "";
  const placeholder = typeof el.placeholder === "string" ? el.placeholder : "";
  const value =
    typeof el.value === "number" ? String(el.value) : typeof el.value === "string" ? el.value : "";
  return html`
    <div class="ac-input">
      ${label ? html`<label class="ac-input__label">${label}</label>` : nothing}
      <input class="ac-input__field" type="number" placeholder="${placeholder}" .value="${value}" readonly />
    </div>
  `;
}

function renderInputDate(el: ACElement): TemplateResult {
  const label = typeof el.label === "string" ? el.label : "";
  const value = typeof el.value === "string" ? el.value : "";
  return html`
    <div class="ac-input">
      ${label ? html`<label class="ac-input__label">${label}</label>` : nothing}
      <input class="ac-input__field" type="date" .value="${value}" readonly />
    </div>
  `;
}

function renderInputTime(el: ACElement): TemplateResult {
  const label = typeof el.label === "string" ? el.label : "";
  const value = typeof el.value === "string" ? el.value : "";
  return html`
    <div class="ac-input">
      ${label ? html`<label class="ac-input__label">${label}</label>` : nothing}
      <input class="ac-input__field" type="time" .value="${value}" readonly />
    </div>
  `;
}

function renderInputToggle(el: ACElement): TemplateResult {
  const title = typeof el.title === "string" ? el.title : "";
  const value = typeof el.value === "string" ? el.value : "false";
  const checked = value === "true" || value === el.valueOn;
  return html`
    <div class="ac-input ac-input--toggle">
      <label class="ac-input__toggle-label">
        <input type="checkbox" .checked="${checked}" disabled />
        <span>${title}</span>
      </label>
    </div>
  `;
}

function renderInputChoiceSet(el: ACElement): TemplateResult {
  const label = typeof el.label === "string" ? el.label : "";
  const choices = Array.isArray(el.choices) ? (el.choices as ACElement[]) : [];
  const value = typeof el.value === "string" ? el.value : "";
  const isMultiSelect = el.isMultiSelect === true;
  const style = el.style === "expanded" ? "expanded" : "compact";
  const selectedValues = new Set(value.split(",").map((v) => v.trim()));

  if (style === "expanded" || isMultiSelect) {
    return html`
      <div class="ac-input">
        ${label ? html`<label class="ac-input__label">${label}</label>` : nothing}
        <div class="ac-input__choices">
          ${choices.map((c) => {
            const cVal = typeof c.value === "string" ? c.value : "";
            const cTitle = typeof c.title === "string" ? c.title : cVal;
            const isSelected = selectedValues.has(cVal);
            return html`
              <label class="ac-input__choice">
                <input type="${isMultiSelect ? "checkbox" : "radio"}" .checked="${isSelected}" disabled />
                <span>${cTitle}</span>
              </label>
            `;
          })}
        </div>
      </div>
    `;
  }

  return html`
    <div class="ac-input">
      ${label ? html`<label class="ac-input__label">${label}</label>` : nothing}
      <select class="ac-input__field" disabled>
        ${choices.map((c) => {
          const cVal = typeof c.value === "string" ? c.value : "";
          const cTitle = typeof c.title === "string" ? c.title : cVal;
          return html`<option value="${cVal}" ?selected="${selectedValues.has(cVal)}">${cTitle}</option>`;
        })}
      </select>
    </div>
  `;
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

function renderActions(actions: ACElement[]): TemplateResult {
  return html`
    <div class="ac-actions">
      ${actions.map((a) => renderAction(a))}
    </div>
  `;
}

function renderAction(a: ACElement): TemplateResult | typeof nothing {
  const type = typeof a.type === "string" ? a.type : "";
  const title = typeof a.title === "string" ? a.title : "";

  switch (type) {
    case "Action.OpenUrl": {
      const url = typeof a.url === "string" ? a.url : "";
      if (!url) {
        return nothing;
      }
      return html`<button
        class="ac-action ac-action--link"
        type="button"
        @click=${() => openExternalUrlSafe(url)}
      >${title}</button>`;
    }

    case "Action.Submit":
    case "Action.Execute": {
      return html`<button
        class="ac-action ac-action--submit"
        type="button"
        @click=${() => dispatchCardAction(a)}
      >${title}</button>`;
    }

    case "Action.ShowCard": {
      const card = a.card as ACElement | undefined;
      const body = card && Array.isArray(card.body) ? card.body : [];
      const cardActions = card && Array.isArray(card.actions) ? (card.actions as ACElement[]) : [];
      return html`
        <details class="ac-showcard">
          <summary class="ac-action ac-action--link">${title}</summary>
          <div class="ac-showcard__body">
            ${renderElements(body as unknown[])}
            ${cardActions.length ? renderActions(cardActions) : nothing}
          </div>
        </details>
      `;
    }

    case "Action.ToggleVisibility": {
      // Toggle visibility requires DOM state tracking; render as a toggle button
      const targetIds = Array.isArray(a.targetElements) ? a.targetElements : [];
      return html`<button
        class="ac-action ac-action--link"
        type="button"
        @click=${(e: Event) => {
          const card = (e.currentTarget as HTMLElement).closest(".ac-card");
          if (!card) {
            return;
          }
          for (const target of targetIds) {
            const id =
              typeof target === "string"
                ? target
                : typeof target === "object" && target
                  ? ((target as ACElement).elementId as string)
                  : "";
            if (!id) {
              continue;
            }
            const el = card.querySelector(`[data-ac-id="${id}"]`);
            if (el) {
              el.style.display = el.style.display === "none" ? "" : "none";
            }
          }
        }}
      >${title}</button>`;
    }

    default:
      return nothing;
  }
}

/** Dispatch a custom event for card action routing. */
function dispatchCardAction(action: ACElement): void {
  const detail = {
    type: action.type,
    title: action.title,
    data: action.data,
    verb: action.verb,
  };
  window.dispatchEvent(new CustomEvent("ac-action", { detail, bubbles: true }));
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sizeToClass(size: unknown): string {
  switch (size) {
    case "Small":
      return "ac-size-sm";
    case "Medium":
      return "ac-size-md";
    case "Large":
      return "ac-size-lg";
    case "ExtraLarge":
      return "ac-size-xl";
    default:
      return "ac-size-default";
  }
}

function imageSizeClass(size: unknown): string {
  switch (size) {
    case "Small":
      return "ac-img-sm";
    case "Medium":
      return "ac-img-md";
    case "Large":
      return "ac-img-lg";
    default:
      return "ac-img-auto";
  }
}
