// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyFeatherlessConfig,
  buildFeatherlessModelDefinition,
  buildFeatherlessProvider,
  FEATHERLESS_BASE_URL,
  FEATHERLESS_DEFAULT_MODEL_REF,
  FEATHERLESS_MODEL_CATALOG,
} from "../../extensions/featherless/api.js";
