// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export { buildKimiCodingProvider } from "../../extensions/kimi-coding/api.js";
export {
  KIMI_CODING_DEFAULT_CONTEXT_WINDOW,
  KIMI_CODING_DEFAULT_MAX_TOKENS,
  KIMI_MODEL_CATALOG,
} from "../../extensions/kimi-coding/api.js";
