// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
import type { PluginSdkFacadeTypeMap } from "../generated/plugin-sdk-facade-type-map.generated.js";
type FacadeEntry = PluginSdkFacadeTypeMap["nexos"];
type FacadeModule = FacadeEntry["module"];
import {
  createLazyFacadeArrayValue,
  loadBundledPluginPublicSurfaceModuleSync,
} from "./facade-runtime.js";

function loadFacadeModule(): FacadeModule {
  return loadBundledPluginPublicSurfaceModuleSync<FacadeModule>({
    dirName: "nexos",
    artifactBasename: "api.js",
  });
}
export const applyNexosConfig: FacadeModule["applyNexosConfig"] = ((...args) =>
  loadFacadeModule()["applyNexosConfig"](...args)) as FacadeModule["applyNexosConfig"];
export const buildNexosModelDefinition: FacadeModule["buildNexosModelDefinition"] = ((...args) =>
  loadFacadeModule()["buildNexosModelDefinition"](
    ...args,
  )) as FacadeModule["buildNexosModelDefinition"];
export const buildNexosProvider: FacadeModule["buildNexosProvider"] = ((...args) =>
  loadFacadeModule()["buildNexosProvider"](...args)) as FacadeModule["buildNexosProvider"];
export const discoverNexosModels: FacadeModule["discoverNexosModels"] = ((...args) =>
  loadFacadeModule()["discoverNexosModels"](...args)) as FacadeModule["discoverNexosModels"];
export const NEXOS_BASE_URL: FacadeModule["NEXOS_BASE_URL"] = loadFacadeModule()["NEXOS_BASE_URL"];
export const NEXOS_DEFAULT_MODEL_REF: FacadeModule["NEXOS_DEFAULT_MODEL_REF"] =
  loadFacadeModule()["NEXOS_DEFAULT_MODEL_REF"];
export const NEXOS_MODEL_CATALOG: FacadeModule["NEXOS_MODEL_CATALOG"] = createLazyFacadeArrayValue(
  () => loadFacadeModule()["NEXOS_MODEL_CATALOG"] as unknown as readonly unknown[],
) as FacadeModule["NEXOS_MODEL_CATALOG"];
